name: library_management_app
description: A Library Management App with Flutter frontend and Django backend.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  get: ^4.7.3
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^19.5.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.7
  iconsax_flutter: ^1.0.1
  image_picker: ^1.2.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/all_books/
    - assets/fiction/
    - assets/images/
    - assets/logo/
    - assets/person/
    - assets/science/
    - assets/technology/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#1056be"
  image: assets/logo/android12splash.png
  branding: assets/logo/android12splash.png
  color_dark: "#1056be"
  image_dark: assets/logo/android12splash.png
  branding_dark: assets/logo/android12splash.png

  android_12:
    image: assets/logo/android12splash.png
    icon_background_color: "#1056be"
    image_dark: assets/logo/android12splash.png
    icon_background_color_dark: "#1056be"

  web: false